<a href="https://colab.research.google.com/github/mujahidmy/data-science-we1/blob/main/tutorialwe3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
y=np.random.rand(3,4)
print(y)

[[0.10652473 0.05071561 0.44328182 0.95136127]
 [0.19001416 0.87319672 0.48302592 0.17333516]
 [0.50036933 0.01873787 0.61126108 0.36581633]]


In [ ]:
x=np.ones((3,3))
y=np.zeros((3,3))
print((x),("\n"),(y))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x=np.random.rand(6,3)
print(x)
x=x.T
print("\n",x)

[[0.38019645 0.76546428 0.26806762]
 [0.61061943 0.38095821 0.30336343]
 [0.66287569 0.71932403 0.87453685]
 [0.05034056 0.29119535 0.41024872]
 [0.2586117  0.03372237 0.57799842]
 [0.87637562 0.9568006  0.45737905]]

 [[0.38019645 0.61061943 0.66287569 0.05034056 0.2586117  0.87637562]
 [0.76546428 0.38095821 0.71932403 0.29119535 0.03372237 0.9568006 ]
 [0.26806762 0.30336343 0.87453685 0.41024872 0.57799842 0.45737905]]


In [ ]:
n,m,p = 3,4,5
x=np.random.rand(n,p)
y=np.random.rand(p,m)
z=np.dot(x,y)
print(z)

[[1.53317076 1.64551524 1.64427686 2.04834538]
 [1.83111836 1.27525785 1.66239809 2.28721071]
 [1.21358743 1.02593362 1.32625438 1.60822684]]
